version: 1.0.{build}
environment:
install:
- cmd: nuget sources add -Name LitiumNugetFeed -Source https://nuget.litium.com/nuget/ -UserName %litium_nuget_user% -Password %litium_nuget_password%
before_build:
- cmd: nuget restore -Verbosity quiet
build:
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: xlC8lzfO3RDrC0seyo/FgrHZIh1S5gNvZk2Ns0RozOt+18BQRR52xc88tD6hEBeC
  skip_symbols: false
  artifact: /.*\.nupkg/